[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "python3 app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "always"

[env]
PORT = "8000"
