[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python backend/app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "always"

[env]
PORT = "8000"
