services:
  - type: web
    name: sneaker-auth-api
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /api/health
    autoDeploy: true
