services:
  - type: web
    name: sneaker-auth-api
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: MODEL_DOWNLOAD_URL
        value: "https://github.com/MeshariAlbati/sneaker-auth-app/releases/download/v1.0.0/sneaker_model_production.pth"
    healthCheckPath: /api/health
    autoDeploy: true
